
name: CI/CD

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    # The Secrect Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.E2E_ENV_SECRETS }} | base64 -d
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.E2E_ENV_SECRETS}} | base64 | sed 's/./& /g'
